# Generated by Django 4.2.5 on 2023-09-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='status',
            new_name='level',
        ),
    ]
